(cl:in-package TonyPi-msg)
(cl:export '(HEADER-VAL
          HEADER
          OFFSET-VAL
          OFFSET
          STATES-VAL
          STATES
          POS-VAL
          POS
          TARGET1-VAL
          TARGET1
          TARGET2-VAL
          TARGET2
          TARGET3-VAL
          TARGET3
          TARGET4-VAL
          TARGET4
          TARGET5-VAL
          TARGET5
          TARGET6-VAL
          TARGET6
          TARGET7-VAL
          TARGET7
          TARGET8-VAL
          TARGET8
          TARGET9-VAL
          TARGET9
          TARGET10-VAL
          TARGET10
          ISINPOSITION-VAL
          ISINPOSITION
          CURRENTLINE-VAL
          CURRENTLINE
))